spring:
  config:
    import: optional:file:.env.properties  # 환경 변수 파일 import (경로 수정 완료)
  jackson:
    serialization:
      write-dates-as-timestamps: false   # 숫자 타임스탬프(에포크) 사용 금지
    date-format: yyyy-MM-dd'T'HH:mm:ss
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false         # 수동 커밋
      allow-auto-create-topics: false   # 토픽 자동 생성 금지(운영 습관)
      auto-offset-reset: latest         # 필요시 earliest
      max-poll-records: 500
      fetch-min-bytes: 1
      fetch-max-wait-ms: 500
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      enable-idempotence: true
      retries: 10
      linger-ms: 20                     # 묶음 전송
      batch-size: 131072                # 128KB
      compression-type: lz4             # 네트워크 절약(옵션)
    listener:
      concurrency: 3                    # 컨슈머 스레드 수 (파티션 수에 맞춰 조정)


springdoc:
  override-with-generic-response: false

logging:
  level:
    org.springframework.boot.context.config: DEBUG  # ⬅️ 추가됨
