spring:
  config:
    import: optional:file:.env.properties
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
  jpa:
    show-sql: off
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      allow-auto-create-topics: false
      auto-offset-reset: latest
      max-poll-records: 500
      fetch-min-bytes: 1
      fetch-max-wait-ms: 500
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      enable-idempotence: true
      retries: 10
      linger-ms: 20
      batch-size: 131072
      compression-type: lz4
    listener:
      concurrency: 3
      ack-mode: manual

springdoc:
  override-with-generic-response: false

logging:
  config: classpath:logback-spring.xml
  # level:
  #   org.springframework.boot.context.config: DEBUG
  #   org.springframework.security: DEBUG

server:
  forward-headers-strategy: framework
