spring:
  config:
    import: optional:file:.env.properties  # 환경 변수 파일 import (경로 수정 완료)
  jackson:
    serialization:
      write-dates-as-timestamps: false   # 숫자 타임스탬프(에포크) 사용 금지
    date-format: yyyy-MM-dd'T'HH:mm:ss
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  override-with-generic-response: false

logging:
  level:
    org.springframework.boot.context.config: DEBUG  # ⬅️ 추가됨
    org.springframework.security: DEBUG   # ⬅️ 추가

server:
  forward-headers-strategy: framework